### PR TITLE
Pure JavaScript solution and image fix

### PR DESCRIPTION
**Pull request by olfek**

### CODE REVIEW

**Comment by olfek** [comment]
@f Would you like me to resolve the conflict or are you already doing it?

**Comment by f** [comment]
Please do :)

11 Nis 2017 Sal 15:47 tarihinde olfek <notifications@github.com> şunu yazdı:

**Comment by olfek** [comment]
@f [This pull request] doesn't actually work, no images are generated. Would you like me to undo it?

**Comment by olfek** [comment]
@f [This pull request](https://github.com/f/loremjs/pull/10) doesn't actually work, no images are generated. Would you like me to undo it?

It is instead, better to use the original service that moved: http://lorempixel.com/

**Comment by olfek** [comment]
@f I undid [this pull request](https://github.com/f/loremjs/pull/10) because it didn't work. This is now ready to merge. Pure JS! Woo!

**Comment by olfek** [comment]
@f You can either merge the PR that reverts that PR or just merge this, which will do it anyway and save me having to fix merge conflicts again.

**Comment by olfek** [comment]
@f If you want me to change something, let me know.

**Comment by olfek** [comment]
@f Kindly, please don't ignore this merge request. The least you could do is provide some feedback if you don't wish to merge it.

**Comment by f** [comment]
Done. Phew.  Thank you!

**Pull request merged**
